dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - '14'
cache:
  directories:
    - ./node_modules
install:
  - npm install
before_script:
  - npm run seed
script:
  - npm run lint
deploy:
  provider: heroku:git
  api_key: HEROKU_API_KEY
  app: recall-api
  on:
    branch: master
  edge: true