dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - '16'
cache:
  directories:
    - './node_modules'
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: heroku:git
  api_key:
    secure: aZG5A8gQokOnbta1q1f7jGMIclenqeuDQSzW+R6Ze47HW3BRJZKiVmJET5gIqP3fnZmfEK7GyxLd916KAv/ESDwj6DD1u5c3t8pzzszHEOLRWWkSXmifMrCtPgwmx3vhZBgEi0KNFRvS+VkyEA+h3estwNAF3Ce5V3s/lLutLwa2DGpah3ym7VegkuyZVNABzIJSBkvtPkt+L8d+pBas53oI9tBleVvF7cN/0lYHimHO97ViNFzEmteWhW8XIpnhtObDpEfduDC5LXG6dW09IrmPGy9TMKZ3SiXYpHLgCwfdZue0Xfe4Q3kOlo63We17Yre/HAZvlssRHBg1pEEH7KgK6OpGtq2b5en1rvRZYKb0hYg9xU0Gb1q3tBSLYtRBrGU5qxIFK4/Z2B83kyFFL/q5amLSkhkuBNZ+txa0eS/x/eilXamF3J559cFw0i3GKTX2wW1N5SWB6ny3fE2tb+FMf4Bi8sdAtpxbogocQ4m2HyvxbKdeP2ufspg/F4NtDEnnsoTlRa5ZMMWUCDvoep89z0tSzEWW8Z/P2NGPP/d03cx7L1HUuWMWaqZC+7JFvAm7aRDZnRhlvggTgKkeZgBB4Km/3K9j0oR2SJN/icUHVYVZRzySHwGk9wLK6TE5I7EV2Q1j+h7YF07rMZpada9bDn1EgzY8durUBTznaGg=
  app: recall-app-api
  on:
    branch: master
  edge: true
