dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
- '14'
cache:
  directories:
  - "./node_modules"
install:
- npm install
script:
- npm run lint
deploy:
  provider: heroku:git
  api_key:
    secure: CqQPWfKfv13A5YdwMT1eRkZ4jAqwQ0F44ZURjn+5tzDnZu4f1m9yfj8vhYjGmOVMeEe/py/MUGak4R6HG3FVGnT1Ofh+2BU8YbgMXBOssaKZf0BYl3Eoo01l3H6vlAGAh69m417brjCWY0SsC3M4mOBqbAGAMCxi/++rx8lVPLHTChFmqTl6lwh4YYq5uohhSYlQEvNYqkARP6dXH5ovjJA9eXdALvDGfbuL6lMYlZx4vKEerEJI2XAncrvy3ValRkFV/jePicp7iU//vU6lMm2XZUbET7kmkPlaRK/DP6XDpRoU8WIu1Ud4Oli38juUUYlV+eEzuISbbP88f0EXatZ7NmeLdZlHTGc7NP250J2o0ohDR6uB0WXMwZujrE3mJiGgXHqpAusPkCOkxPV3egyjDf/O0O7P1tOXA1jWVwmGFS/wHYwT8TsfvZ+o+QVob+KlyJjwvGazgEcjcg8SDrSDrGWP3IhIeDkp3oGlkrILP9ALcFLA7QPB20dVKhUywaKnEdbhWxPyiG9i+oBh0DRpzbBF5LtX86DELUmfi8CYyY7fFi0YRLetdkm0IKlJsaHICJm5imqyBisRLrF0NQp9YxMCuYvvXB2pN+MfjeYPoNxDdv0vQkk2HnF1WXBEYK8w4nWHj5pDFkShfyB3W+sok/T38tq9eD/DlPF+vso=
  app: recall-app-api
  on:
    branch: master
  edge: true
