dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - '16'
cache:
  directories:
    - './node_modules'
install:
  - npm install
script:
  - npm run lint
deploy:
  provider: heroku:git
  api_key:
    secure: fxzk03sp+1k+EGTu0bCLGeEVria1I6JRYEergCGp0b5UuQWTeVW4TrDjfsWZACiO+dg43Fg/ULOGiB6d0w8m50s1F6Q/LvBqSGlHSJo9+iyA1qvWxqlCkPm8+pqfauc3RAD5jAi/mnGj2ratGZLoT4kyx8Ib2CyBeWiSLvCJ/4yxOORLzFcoPJdZI2Wzulfl9hqTrLFguPT0WeciLy1fWKKAr6XPSPKiSjrhGIHUDmQ/YH2s7nl8FqFlndl5TIa5PQrUExdROqOTDOE15ZBLRrx2QmQjCE1EsWRKEBX32rzOaoSvcB+Pc0r4pJ7VdMBgOuLo5OB/fp629IJ8+LUHx5Q8kUSHn0HXXh4nwptVZPc2tD/3QXdQw1hRiykd50iX8A8u6ADbrayisK5awQEZs6YUH1q6WSA7hX6rW/RCl0MFB2zF6kGk8r6jah4uVpug3CmtmRbG+CbY3BFf8YCzG78MKwEDPrbcWidEhTXacwqMvZFpEr8MHCE8DJrb1nWrD51sex8G7kyDZSBur5zHGOb2a+JFZzvSvigSs8472hjCHwmes51Q7UKBWm6f24ckcyqdHJlUZSB+8hno5yLl4nrizd01S4pStHDHcEtCCrJibxl1VGzHkGGp0KB4zL8t9negnMlzWuorcInsSOaRaT7TRpxhow9snXyrNqjJ1mQ=
  app: recall-app-api
  on:
    branch: master
  edge: true
